version: "3.7"
services:

  last_sprint_bot_dev_mongo:
    image: mongo:4.2
    container_name: last_sprint_bot_dev_mongo
    ports:
      - 6355:27017
    expose:
      - "6355"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    restart: on-failure
    volumes:
      - ./mondodb_data:/data/db
    networks: 
      - last_sprint_bot_dev_network

  last_sprint_bot_dev_mongo_web_view:
    container_name: last_sprint_bot_dev_mongo_web_view
    image: mongo-express
    restart: on-failure
    depends_on:
      - last_sprint_bot_dev_mongo
    ports:
      - 6357:8081
    expose:
      - "6357"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: last_sprint_bot_dev_mongo
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
      ME_CONFIG_SITE_BASEURL: /dbview
    networks: 
        - last_sprint_bot_dev_network

networks: 
    last_sprint_bot_dev_network:
        driver: bridge