sdfhghsgefhfsghdfg
sdf]//kubectl create secret docker-registry NAME --docker-username=user --docker-password=password --docker-email=email [--docker-server=string] [--from-literal=key1=value1] [--dry-run] 
// dockerconfigjson is a base64 encoded string:  cat ~/.docker/config.json | base64 -w 0 
apiVersion: v1
kind: Secret
metadata:
  name:  Name_of_the_Secret
data:
  .dockerconfigjson:  secret
type: kubernetes.io/dockerconfigjsondf
//kubectl create secret docker-registry NAME --docker-username=user --docker-password=password --docker-email=email [--docker-server=string] [--from-literal=key1=value1] [--dry-run] 
// dockerconfigjson is a base64 encoded string:  cat ~/.docker/config.json | base64 -w 0 
apiVersion: v1
kind: Secret
metadata:
  name:  Name_of_the_Secret
data:
  .dockerconfigjson:  secret
type: kubernetes.io/dockerconfigjsonxfs
df
//kubectl create secret docker-registry NAME --docker-username=user --docker-password=password --docker-email=email [--docker-server=string] [--from-literal=key1=value1] [--dry-run] 
// dockerconfigjson is a base64 encoded string:  cat ~/.docker/config.json | base64 -w 0 
apiVersion: v1
kind: Secret
metadata:
  name:  Name_of_the_Secret
data:
  .dockerconfigjson:  secret
type: kubernetes.io/dockerconfigjsondfsd
env:
  - name:  ENV_VAR
    valueFrom:
      secretKeyRef:
        name:  name
        key:  keydf
        ]//kubectl create secret docker-registry NAME --docker-username=user --docker-password=password --docker-email=email [--docker-server=string] [--from-literal=key1=value1] [--dry-run] 
        // dockerconfigjson is a base64 encoded string:  cat ~/.docker/config.json | base64 -w 0 
        apiVersion: v1
        kind: Secret
        metadata:
          name:  Name_of_the_Secret
        data:
          .dockerconfigjson:  secret
        type: kubernetes.io/dockerconfigjsonaasd


        ports:
        - name:  Port Name
          port:  Port
          targetPort:  Target port